services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - 6006:5432
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
